#pragma once

#include "arch.h"
#include "config.h"
#include "str.h"
#include "util.h"

enum { MG_FS_FAIL = 0, MG_FS_FILE = 1, MG_FS_DIR = 2 };

// Filesystem API functions
struct mg_fs {
  // Returns MG_FS_* and populates file size and modification time
  int (*info)(const char *path, size_t *size, time_t *mtime);

  // Calls fn() for every directory entry, allowing to list a directory
  // Returns the number of files listed
  size_t (*list)(const char *path, bool recursive,
                 void (*fn)(const char *, void *), void *);

  // Read a file at offset ofs, return number of bytes read
  size_t (*reader)(const char *path, size_t ofs, void *buf, size_t len);

  // Write to a file at offset ofs, return number of bytes written
  // Writing to a non-existing directory creates intermediate directories
  size_t (*writer)(const char *path, size_t ofs, const void *buf, size_t len);

  // Delete a file or directory (recursively), aka rm -rf
  bool (*del)(const char *path);
};

// Predefined APIs. Users can make their own!
extern struct mg_fs mg_fs_std;   // Standard ISO C fopen/fclose/...
extern struct mg_fs mg_fs_mem;   // See tutorials/core/embedded-filesystem
extern struct mg_fs mg_fs_fat;   // FAT FS

// Helper functions that reads a file into RAM and returns as mg_str
struct mg_str mg_file_read(struct mg_fs *fs, const char *path);
bool mg_file_write(struct mg_fs *fs, const char *path, const void *, size_t);

// A piece of memory (flash or RAM) represented as a file
struct mg_mem_file {
  const char *path;
  const unsigned char *data;
  size_t size;   // Data size
  time_t mtime;  // Modification time
};

// Global variable that points to the array of memory files. It can be
// changed to point to the user-defined file array. The last element
// should have NULL path.
//
// static const struct mg_mem_file my_files[] = {
//   {"/web_root/index.html", "hi", 2, 0},
//   {NULL, NULL, 0, 0},
// };
// mg_mem_files = my_files;
extern const struct mg_mem_file *mg_mem_files;

struct mg_str mg_unpacked(const char *path);        // Packed file as mg_str
extern const struct mg_mem_file mg_packed_files[];  // Generated by "pack" util
