COMMON = ../../common

HEADERS = mg_common.h \
          $(COMMON)/platform.h \
          $(COMMON)/platforms/platform_windows.h \
          $(COMMON)/platforms/platform_unix.h \
          $(COMMON)/platforms/platform_esp32.h \
          $(COMMON)/platforms/platform_esp8266.h \
          $(COMMON)/platforms/platform_cc3100.h \
          $(COMMON)/platforms/platform_cc3200.h \
          $(COMMON)/platforms/platform_cc3220.h \
          $(COMMON)/platforms/platform_msp432.h \
          $(COMMON)/platforms/platform_tm4c129.h \
          $(COMMON)/platforms/platform_mbed.h \
          $(COMMON)/platforms/platform_nrf51.h \
          $(COMMON)/platforms/platform_nrf52.h \
          $(COMMON)/platforms/simplelink/cs_simplelink.h \
          $(COMMON)/platforms/platform_wince.h \
          $(COMMON)/platforms/platform_nxp_lpc.h \
          $(COMMON)/platforms/platform_nxp_kinetis.h \
          $(COMMON)/platforms/platform_pic32.h \
          $(COMMON)/platforms/platform_rs14100.h \
          $(COMMON)/platforms/platform_stm32.h \
          $(COMMON)/platforms/lwip/mg_lwip.h \
          $(COMMON)/cs_md5.h \
          $(COMMON)/cs_sha1.h \
          $(COMMON)/cs_time.h \
          $(COMMON)/mg_str.h \
          $(COMMON)/mbuf.h \
          $(COMMON)/cs_base64.h \
          $(COMMON)/str_util.h \
          $(COMMON)/queue.h \
          mg_features.h \
          mg_net_if.h \
          mg_ssl_if.h \
          mg_net.h \
          mg_uri.h \
          mg_util.h \
          mg_http.h \
          mg_http_server.h \
          mg_http_client.h \
          mg_mqtt.h \
          mg_mqtt_server.h \
          mg_dns.h \
          mg_dns_server.h \
          mg_resolv.h \
          mg_coap.h \
          mg_sntp.h \
          mg_socks.h

SOURCES = $(COMMON)/mg_mem.h \
          $(COMMON)/cs_base64.c \
          $(COMMON)/cs_dbg.h \
          $(COMMON)/cs_dbg.c \
          $(COMMON)/cs_dirent.h \
          $(COMMON)/cs_dirent.c \
          $(COMMON)/cs_time.c \
          $(COMMON)/cs_endian.h \
          $(COMMON)/cs_md5.c \
          $(COMMON)/cs_sha1.c \
          $(COMMON)/mbuf.c \
          $(COMMON)/mg_str.c \
          $(COMMON)/str_util.c \
          mg_net.c \
          mg_net_if_socket.h \
          mg_net_if_socks.h \
          mg_net_if.c \
          mg_net_if_null.c \
          mg_net_if_socket.c \
          mg_net_if_socks.c \
          mg_ssl_if_openssl.c \
          mg_ssl_if_mbedtls.c \
          mg_uri.c \
          mg_http.c \
          mg_http_cgi.c \
          mg_http_ssi.c \
          mg_http_webdav.c \
          mg_http_websocket.c \
          mg_util.c \
          mg_mqtt.c \
          mg_mqtt_server.c \
          mg_dns.c \
          mg_dns_server.c \
          mg_resolv.c \
          mg_coap.c \
          mg_sntp.c \
          mg_socks.c \
          $(COMMON)/platforms/cc3200/cc3200_libc.c \
          $(COMMON)/platforms/msp432/msp432_libc.c \
          $(COMMON)/platforms/nrf5/nrf5_libc.c \
          $(COMMON)/platforms/simplelink/sl_fs_slfs.h \
          $(COMMON)/platforms/simplelink/sl_fs_slfs.c \
          $(COMMON)/platforms/simplelink/sl_fs.c \
          $(COMMON)/platforms/simplelink/sl_socket.c \
          $(COMMON)/platforms/simplelink/sl_mg_task.c \
          $(COMMON)/platforms/simplelink/sl_net_if.h \
          $(COMMON)/platforms/simplelink/sl_net_if.c \
          $(COMMON)/platforms/simplelink/sl_ssl_if.c \
          $(COMMON)/platforms/lwip/mg_lwip_net_if.h \
          $(COMMON)/platforms/lwip/mg_lwip_net_if.c \
          $(COMMON)/platforms/lwip/mg_lwip_ev_mgr.c \
          $(COMMON)/platforms/wince/wince_libc.c \
          $(COMMON)/platforms/pic32/pic32_net_if.h \
          $(COMMON)/platforms/pic32/pic32_net_if.c \
          $(COMMON)/platforms/windows/windows_direct.c
