name: MemBrowse PR Comment

on:
  workflow_run:
    workflows: [MemBrowse Memory Report]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion != 'cancelled'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Post combined PR comment
        if: ${{ env.MEMBROWSE_API_KEY != '' }}
        uses: membrowse/membrowse-action/comment-action@v1
        with:
          api_key: ${{ secrets.MEMBROWSE_API_KEY }}
          commit: ${{ github.event.workflow_run.head_sha }}
        env:
          MEMBROWSE_API_KEY: ${{ secrets.MEMBROWSE_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
