name: On demand ad hoc test
on:
  workflow_dispatch:
env:
  IPV6: 0
jobs:
  bsd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang, g++, clang++]
    name: bsd CC=${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v5
      with: { fetch-depth: 2 }
    - uses: webfactory/ssh-agent@v0.10.0
      with:
            ssh-private-key: ${{ secrets.HEALTH_TESTS_SSH_KEY }}
    - run: |
        source ./test/setup_ga_network.sh
        make -C test/bsd shm_tap_bridge
        test/bsd/shm_tap_bridge &
        sleep 2
        make -C test/bsd
